version: "3"
services:
  phreaking-core:
    build: .
    # The code should be copied into the container using COPY.
    # Mount the data folder writable, so that information can be persisted across restarts.
    volumes:
      - ./data/:/data:rw
    # Define the port mapping (external:internal port)
    ports:
      - "3399:3399"
    entrypoint: /core-entrypoint.sh
  phreaking-ue:
    build: .
    # Define the port mapping (external:internal port)
    ports:
      - "6060:6060"
      - "9933:9933"
    entrypoint: /ue-entrypoint.sh
