version: "3"
services:
  phreaking-core:
    build:
      context: .
      target: core
    ports:
      - "3399:3399"
    environment:
      - SIM_KEY=passphrasewhichneedstobe32bytes!
  phreaking-ue:
    build:
      context: .
      target: ue
    ports:
      - "6060:6060"
      - "9933:9933"
    volumes:
      - ./data/:/service/data:rw
    environment:
      - GRPC_PASS=ultrasecretpasswordthatwillneverbebroken
      - SIM_KEY=passphrasewhichneedstobe32bytes!