version: "3"
services:
  # Give your container proper names!
  phreaking-checker:
    build: .
    # The checker runs a HTTP interfaces, so we need to map port 3031 to the outside (port 8000).
    ports:
      - 3303:3303
    environment:
      - PHREAKING_GRPC_PASS=${PHREAKING_GRPC_PASS}
      - PHREAKING_SIM_KEY=${PHREAKING_SIM_KEY}
      - REDIS_PASS=asimplesentenceisbetter
  phreaking-db:
    image: redis:7-alpine
    restart: always
    volumes:
      - ./data:/data:rw
    command: redis-server --save 20 1 --loglevel warning --requirepass asimplesentenceisbetter
